AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Estoque Service - Inventory Management Microservice'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  DatabasePassword:
    Type: String
    NoEcho: true
    Default: dev123456
    Description: Database password

  DatabaseUrlParameter:
    Type: AWS::SSM::Parameter::Value<String>    # ou <SecureString>
    Default: /secret/database_url

  InternalApiKeyParameter:
    Type: AWS::SSM::Parameter::Value<String>    # ou <SecureString>
    Default: /secret/internal_api_key

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: INFO
        DATABASE_URL: !Ref DatabaseUrlParameter
        INTERNAL_API_KEY: !Ref InternalApiKeyParameter
    Tags:
      Service: estoque    # tag aplicada a todas as Lambdas
    VpcConfig:
      SecurityGroupIds:
        - sg-0023175edfd49ca18
      SubnetIds:
        - subnet-0f12951fa6cccef8e #privada
        - subnet-0d9dc74d2a9c8c4f6 #privada

Resources:
  # 1) API Gateway explícito
  EstoqueApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaAuth
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          LambdaAuth:
            FunctionArn: !ImportValue
              Fn::Sub: 'AuthFunctionArn'
            Identity:
              Header: Authorization
      Tags:
        Service: estoque   # tag aplicada ao API Gateway

  # === INVENTORY CRUD FUNCTIONS ===

  CreateInventoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.create_inventory_handler
      Description: Create new inventory record
      Events:
        CreateInventory:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/estoque
            Method: POST

  GetInventoryByProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.get_inventory_by_product_handler
      Description: Get inventory by product ID
      Events:
        GetInventoryByProduct:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/inventory/product/{produto_id}
            Method: GET

  ListInventoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.list_inventory_handler
      Description: List all inventory with pagination
      Events:
        ListInventory:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/inventory
            Method: GET

  # === STOCK MOVEMENT FUNCTIONS ===

  AddStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.add_stock_handler
      Description: Add stock to product
      Events:
        AddStock:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/inventory/add-stock
            Method: POST

  RemoveStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.remove_stock_handler
      Description: Remove stock from product
      Events:
        RemoveStock:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/inventory/remove-stock
            Method: POST

  AdjustStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.adjust_stock_handler
      Description: Adjust stock to new quantity
      Events:
        AdjustStock:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/inventory/adjust-stock
            Method: POST

  # === REPORTS FUNCTIONS ===

  LowStockReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.low_stock_report_handler
      Description: Get low stock report
      Events:
        LowStockReport:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/inventory/reports/low-stock
            Method: GET

  OutOfStockReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.out_of_stock_report_handler
      Description: Get out of stock report
      Events:
        OutOfStockReport:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/inventory/reports/out-of-stock
            Method: GET

  # === HEALTH CHECK (público) ===

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.handlers.estoque_handler.health_check_handler
      Description: Health check endpoint
      Events:
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref EstoqueApi
            Path: /api/v1/health
            Method: GET
            Auth:
              Authorizer: NONE

Outputs:
  EstoqueApiUrl:
    Description: "API Gateway endpoint URL for Estoque service"
    Value: !Sub "https://${EstoqueApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: "estoque-api-url"

  CreateInventoryFunctionName:
    Description: "Create Inventory Function Name"
    Value: !Ref CreateInventoryFunction
    Export:
      Name: "create-inventory-function"

  ListInventoryFunctionName:
    Description: "List Inventory Function Name"
    Value: !Ref ListInventoryFunction
    Export:
      Name: "list-inventory-function"
